site_name: HoneypotDB Documentation
site_url: https://docs.honeypotdb.com
site_descripion: HoneypotDB's usage documentation.
site_author: HoneypotDB

copyright: Copyright 2023 HoneypotDB
repo_url: https://github.com/HoneypotDB/docs.honeypotdb.com
theme:
  logo: https://static.honeypotdb.com/img/logo/logo_white.png
  name: material
  highlightjs: true
  include_homepage_in_sidebar: true
  palette: 

    # Palette toggle for light mode
    - scheme: hpdb
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: hpdb
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
   - glightbox

extra_css:
    - stylesheets/extra.css

nav:

  - 'Home': 'index.md'

  - 'Guides and Tutorials':
    - 'Getting started': guides/getting-started.md
    # - 'Using the Search UI': guides/using-the-search-ui.md
    # - 'Creating an API key': guides/creating-an-api-key.md
    # - 'Querying with the Search API': guides/querying-with-the-search-api.md

  - 'Core Capabilities':
    - 'Signals': 
      - 'Overview': 'capabilities/signals/overview.md'
    - 'Search':
      - 'Overview': 'capabilities/search/overview.md'
      - 'Query Langauge': 'capabilities/search/query-language.md'
    # - 'Score': capabilities/score.md
    # - 'Malware': capabilities/malware.md
    # - 'Monitoring': capabilities/monitoring.md

  # - 'Threat Intelligence':
  #   - 'Severity Reports': intelligence/severity.md
  #   - 'Indicator Lists': intelligence/lists.md

  # - 'Honeypots':
  #   - 'Our Honeypot Network': 'honeypots/network.md'
  #   - 'Types of Honeypots': 'honeypots/types.md'
